spring:
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/test?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySize=999999&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    # profileSQL=true로 설정하면 jdbcTemplate이 들고있는 쿼리를 콘솔 로그로 출력한다
    hikari:
      maximum-pool-size: 20
    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate:
#      ddl-auto: create
  profiles:
    active: local

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  servlet:
    context-path: /test